/*
 *	main.c
 *	Created:	02.04.2020
 *	Author:		Thomas Hofmann
 */

#include "EL-Robot.h"
#include "LCD_MCP23008_16MHz.h"

int main(void)
{
	//Initialization
	set_fuses();			//JTAG disable and CPU-Speed to 16MHz
	init();					//Init timers and set pin modes
	PORTC |= IO_RESET;		//Port expander on
	TWBR = 12;				//TWBR=12, TWPS=0, TWSR per default,f_SCL = 400 kHz
	I2C_init();				//I2C Initialization
	sei();					//Global interrupt enable
	
	//LCD_init();
	//LCD_cmd(LCD_INIT);
	//LCD_cmd(LCD_CLEAR);
	
	lineFollower_init();
	
	//driveSpeed is very inaccurate at lower speeds, due to bad HW design:
	//Too little encoder pulses per revolution (15), no way to determine the direction of the wheel,
	//Non linear continuous servos and and the fact that they always de-calibrate them selves make this function
	//almost useless at lower speed and at acceleration, maybe stepper motors next time,
	//or at least a better encoder with simple DC-motors, i know expensive and difficult to realize at such small scale
	
	//Furthermore, there aren't enough timers on th 32u4 to generate the 38kHz for the infrared LEDs
	//It would be possible to utilize timer 0, but then, how do you time other stuff
	//It would have to be generated by software with something like micros instead of millis(very expensive),
	//maybe in the next version of this program
	
	//To calibrate the line follower, turn the potentiometers all the way to the right and then a LITTLE bit to the left
	//This is to ensure the highest dynamic range
	
    while(1)
    {	
		//driveSpeed(50,50);				//Drive the robot with 50mm/s
		//driveDistance(200,200,200,200);	//Drive the robot with 200mm/s for 200mm
		followLine();
		showBatteryStatus();
	}
}